const DEFAULT_SUBJECTS = [
  'Mathematics',
  'English',
  'Physics',
  'Chemistry',
  'Biology',
  'ICT',
  'History',
  'Geography',
  'Economics',
  'general science',
  'Social studies',
  'Amharic',
  'Affan Oromo',
  'Tigirigna',
  'Programming',
  'IELTS',
  'TOEFL iBT',
  'Duolingo English Test',
  'PTE Academic',
  'Cambridge English',
  'OET',
  'SAT',
  'ACT',
  'GRE',
  'GMAT',
  'AP Exams',
  'International Baccalaureate (IB)',
];

module.exports = { DEFAULT_SUBJECTS };
